<?php
$mapaBase=array(array('form'=>"id_evento",'objeto'=>"id_evento",'tabla'=>"id_evento"),
				array('form'=>"evento",'objeto'=>"evento",'tabla'=>"evento"),
				array('form'=>"lugar",'objeto'=>"lugar",'tabla'=>"lugar"),
				array('form'=>"detalle",'objeto'=>"detalle",'tabla'=>"detalle"),			
				array('form'=>"fecha_even",'objeto'=>"fecha_even",'tabla'=>"fecha_even"),	
				array('form'=>"activa",'objeto'=>"activa",'tabla'=>"activa")					
			);
?>