<?php
$mapaBase=array(array('form'=>"id_carac",'objeto'=>"id_carac",'tabla'=>"id_carac"),
			array('form'=>"id_tipo_carac",'objeto'=>"id_tipo_carac",'tabla'=>"id_tipo_carac"),
			array('form'=>"titulo",'objeto'=>"titulo",'tabla'=>"titulo"),
			array('form'=>"tipo",'objeto'=>"tipo",'tabla'=>"tipo"),				
			array('form'=>"maximo",'objeto'=>"maximo",'tabla'=>"maximo"),
			array('form'=>"comentario",'objeto'=>"comentario",'tabla'=>"comentario"),
			array('form'=>"lista",'objeto'=>"lista",'tabla'=>"lista"),
			array('form'=>"orden",'objeto'=>"orden",'tabla'=>"orden"),
			array('form'=>"comparacion",'objeto'=>"comparacion",'tabla'=>"comparacion"),
			array('form'=>"publica",'objeto'=>"publica",'tabla'=>"publica")
		);
?>