<?php
$mapaBase=array(array('form'=>"id_personal",'objeto'=>"id_personal",'tabla'=>"id_personal"),
			array('form'=>"tipo_doc",'objeto'=>"tipo_doc",'tabla'=>"tipo_doc"),
			array('form'=>"nro_doc",'objeto'=>"nro_doc",'tabla'=>"nro_doc"),
			array('form'=>"nombres",'objeto'=>"nombres",'tabla'=>"nombres"),
			array('form'=>"apellido",'objeto'=>"apellido",'tabla'=>"apellido"),			
			array('form'=>"fecha_nac",'objeto'=>"fecha_nac",'tabla'=>"fecha_nac"),	
			array('form'=>"domicilio",'objeto'=>"domicilio",'tabla'=>"domicilio"),
			array('form'=>"localidad",'objeto'=>"localidad",'tabla'=>"localidad"),
			array('form'=>"telefono",'objeto'=>"telefono",'tabla'=>"telefono"),
			array('form'=>"celular",'objeto'=>"celular",'tabla'=>"celular"),
			array('form'=>"email",'objeto'=>"email",'tabla'=>"email"),
			array('form'=>"fecha_ing",'objeto'=>"fecha_ing",'tabla'=>"fecha_ing"),
			array('form'=>"fecha_eg",'objeto'=>"fecha_eg",'tabla'=>"fecha_eg"),
			array('form'=>"id_funcion",'objeto'=>"id_funcion",'tabla'=>"id_funcion"),
			array('form'=>"observaciones",'objeto'=>"observaciones",'tabla'=>"observaciones")										
			);
?>
