<?php
$mapaBase=array(array('form'=>"id_log",'objeto'=>"id_log",'tabla'=>"id_log"),
			array('form'=>"fecha",'objeto'=>"fecha",'tabla'=>"fecha"),
			array('form'=>"id_user",'objeto'=>"id_user",'tabla'=>"id_user"),
			array('form'=>"tarea",'objeto'=>"tarea",'tabla'=>"tarea"),
			array('form'=>"id",'objeto'=>"id",'tabla'=>"id"),
			array('form'=>"proceso",'objeto'=>"proceso",'tabla'=>"proceso"),
			array('form'=>"estado",'objeto'=>"estado",'tabla'=>"estado"),
			array('form'=>"observacion",'objeto'=>"observacion",'tabla'=>"observacion")
			);
?>